### ISSUE TITLE
Make a Prototype Galaxy Tool from NetBoxR

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#8]
See documentation: https://planemo.readthedocs.io/en/latest/writing.html

**Comment by cannin** [comment]
@sajo25 do the following: 

* [ ] Make branch for Galaxy-related files 
* [ ] Commit Galaxy XML file
* [ ] Commit galaxy_r.R

**Comment by sajo25** [comment]
Though I originally intended to use the updated R and XML files, I instead chose to build the very first Galaxy tool prototype using the code I submitted as part of the GSoC proposal (as @cannin and @mil2041 advised during our meeting last week). The steps of my work are detailed below.

```
source activate netboxr-env
```

```
git clone https://github.com/gallardoalba/galaxytools
cd galaxytools/tools
mkdir netboxr
cd netboxr
```

I populated the directory with the required files (XML file, R file, tool configuration file, test directory). Then, working in this directory, I ran the command `planemo lint`, which helped me debug and improve the XML code, after which I was eventually able to run the tool on a local Galaxy instance using the command `planemo serve`. Screenshots of the netboxr tool interface can be found below. 

<img width="703" alt="galaxy1" src="https://user-images.githubusercontent.com/28693536/177162063-7cad0b1f-a9ff-4818-8c67-78dbbf1f52ce.PNG">
<img width="704" alt="galaxy2" src="https://user-images.githubusercontent.com/28693536/177162090-b9aa8af1-e66b-4f40-adee-7807bffad3cf.PNG">

Though I still need to refine the tool interface, it contains all necessary elements required for a basic netboxr analysis. However, when attempting to run an analysis for the genes EGFR and TP53 and a cutoff p-value of 0.05, the analysis never completes and the tool eventually stops responding. 

<img width="960" alt="galaxy3" src="https://user-images.githubusercontent.com/28693536/177162110-469b2762-6c1e-446c-9b38-9883e35ae19f.PNG">
<img width="960" alt="galaxy4" src="https://user-images.githubusercontent.com/28693536/177162131-227eb921-c007-47dd-b27c-abb23c51d3bb.PNG">

Using the following command:
```
planemo test
```
I initiate a test that perhaps gives more insight into why the tool published on the local Galaxy doesn't run properly. Namely, it appears that the tool dependencies never get installed:
```
2022-07-04 19:19:26,894 INFO  [galaxy.config] Install database targetting Galaxy's database configuration.
2022-07-04 19:19:27,053 ERROR [galaxy.visualization.genomes] Error reading twobit.loc
Traceback (most recent call last):
  File "/opt/galaxy/galaxy-app/lib/galaxy/visualization/genomes.py", line 212, in reload_genomes
    for line in open(os.path.join(self.app.config.tool_data_path, "twobit.loc")):
IOError: [Errno 2] No such file or directory: '/opt/galaxy/galaxy-app/tool-data/twobit.loc'
2022-07-04 19:19:27,077 INFO  [galaxy.util.handlers] JobConfiguration: No job handler assignment method is set, defaulting to 'db-preassign', set the `assign_with` attribute on <handlers> to override the default
2022-07-04 19:19:27,077 INFO  [galaxy.jobs] Job handler assignment methods set to: db-preassign
2022-07-04 19:19:27,077 INFO  [galaxy.jobs] Tag [_default_] handlers: main
2022-07-04 19:19:27,119 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpqm9Fiu/tool_conf.xml
2022-07-04 19:19:27,149 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpqm9Fiu/shed_tools_conf.xml
2022-07-04 19:19:27,150 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /tmp/tmpqm9Fiu/empty_tool_conf.xml
2022-07-04 19:19:27,263 ERROR [galaxy.tools.data_manager.manager] There was an error parsing your Data Manager config file "./": [Errno 21] Is a directory: './'
No handlers could be found for logger "galaxy.datatypes.display_applications.application"
2022-07-04 19:19:27,558 INFO  [galaxy.jobs] Handler 'main' will load all configured runner plugins
2022-07-04 19:19:27,597 INFO  [galaxy.jobs.handler] job handler stop queue started
2022-07-04 19:19:27,606 INFO  [galaxy.jobs.handler] job handler queue started
2022-07-04 19:19:27,610 INFO  [galaxy.jobs.handler] job handler stop queue started
2022-07-04 19:19:27,625 INFO  [galaxy.app] Galaxy app startup finished (3260.794 ms)
2022-07-04 19:19:27,910 INFO  [galaxy.queue_worker] Binding and starting galaxy control worker for main
2022-07-04 19:19:27,910 INFO  [galaxy.web.stack] Galaxy server instance 'main' is running
/opt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:603: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  'storage.' % (dialect.name, dialect.driver))
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52560)
Traceback (most recent call last):
  File "/opt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1090, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
( netboxr_tool ) > Test-1 ... 2022-07-04 19:19:28,626 INFO  [galaxy.tools.actions] Handled output named output_pdf for tool netboxr_tool (7.997 ms)
2022-07-04 19:19:28,628 INFO  [galaxy.tools.actions] Handled output named output_neighbor for tool netboxr_tool (1.683 ms)
2022-07-04 19:19:28,730 INFO  [galaxy.tools.actions] Added output datasets to history (102.413 ms)
2022-07-04 19:19:28,733 INFO  [galaxy.tools.actions] Setup for job Job[unflushed,tool_id=netboxr_tool] complete, ready to be enqueued (2.236 ms)
2022-07-04 19:19:28,776 INFO  [galaxy.util.handlers] Flushed transaction for Job[id=1,tool_id=netboxr_tool] (41.498 ms)
2022-07-04 19:19:28,776 INFO  [galaxy.util.handlers] (Job[id=1,tool_id=netboxr_tool]) Handler 'main' assigned using 'db-preassign' assignment method
2022-07-04 19:19:29,850 INFO  [galaxy.jobs.handler] (1) Job dispatched
2022-07-04 19:19:29,972 DEBUG [galaxy.tools.deps.conda_util] Executing command: /home/ubuntu/miniconda3/bin/conda create -y --quiet --override-channels --channel iuc --channel conda-forge --channel bioconda --channel defaults --name mulled-v1-8efe184a1028f3ed163f2be9161db4b6172c229a2f65de1769121fdb854c55ba r-base=4.0.0 bioconductor-igraph=1.2.4.1 bioconductor-netboxr=1.6.0 r-optparse=1.6.0

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/iuc/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /iuc/linux-64/repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbab8500b8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)


2022-07-04 19:22:11,086 DEBUG [galaxy.tools.deps.resolvers.conda] Removing failed conda install of [CondaTarget[r-base,version=4.0.0], CondaTarget[bioconductor-igraph,version=1.2.4.1], CondaTarget[bioconductor-netboxr,version=1.6.0], CondaTarget[r-optparse,version=1.6.0]]
2022-07-04 19:22:11,087 DEBUG [galaxy.tools.deps.conda_util] Executing command: /home/ubuntu/miniconda3/bin/conda create -y --quiet --override-channels --channel iuc --channel conda-forge --channel bioconda --channel defaults --name __r-base@4.0.0 r-base=4.0.0
```

The debugging continues indefinitely, and the terminal eventually stops responding.

**Comment by sajo25** [comment]
@mil2041 @cannin If you have any tips on what I can try next (based on the terminal output), please let me know!

**Comment by cannin** [comment]
@sajo25 is this in VirtualBox? Can you access the file: "https://conda.anaconda.org/iuc/linux-64/repodata.json" from the error message within VirtualBox? Could you try this again (maybe there was maintenance going on when you tried).

**Comment by sajo25** [comment]
@cannin thank you for the pointers! Yes, I worked in VirtualBox. I don't think the issue was maintenance because I tried this several times over the course of two days. I've since resolved the issue by installing the dependencies using conda separately from running `planemo serve` and `planemo test`. This also failed multiple times and may be an issue again later on, but I am able to run the tool for now and obtain the expected output, as shown in the screenshots below.

<img width="957" alt="Capture1" src="https://user-images.githubusercontent.com/28693536/177645815-bac9327b-633d-4671-9a62-791b41465a0e.PNG">
<img width="882" alt="capture2" src="https://user-images.githubusercontent.com/28693536/177645819-d94c60bf-95e1-432b-bc93-8437aaa5d364.PNG">
<img width="873" alt="capture3" src="https://user-images.githubusercontent.com/28693536/177645832-def1fb82-c6e5-41ed-bcc4-1a36e16016fc.PNG">

**Comment by cannin** [comment]
@sajo25 have you committed the Galaxy configuration files? And how will Galaxy server (not local) learn about the Conda environment?

**Comment by sajo25** [comment]
@cannin Yes, this is the [commit](https://github.com/mil2041/netboxr/commit/feccb5975bc37c089e3980ef7e3ae1ced0171d8e) with the files required to run the prototype.

I've also created a more advanced version with more analysis and output options that I've tested using the data from the netboxr vignette [(commit)](https://github.com/mil2041/netboxr/commit/73ccc475ded90470c73fce84d704bc4a8a5a8627) for a better comparison, as advised by @mil2041. Unlike the prototype, the newest version accepts newline-delimited, as opposed to tab-delimited, files as input. Screenshots of the tool interface and output can be found below:

<img width="873" alt="galaxy1" src="https://user-images.githubusercontent.com/28693536/178962816-f7ce4a49-a715-457a-bc98-370f1d022dc1.PNG">
<img width="867" alt="galaxy2" src="https://user-images.githubusercontent.com/28693536/178962849-da159d72-371c-40dd-8be6-e927e746cef4.PNG">
<img width="876" alt="galaxy3" src="https://user-images.githubusercontent.com/28693536/178962869-3ce19131-c2c8-4e74-b84c-a1b996a740fe.PNG">
<img width="873" alt="galaxy4" src="https://user-images.githubusercontent.com/28693536/178962897-cf16838b-0061-4615-8a88-1ecf006fa98c.PNG">
<img width="873" alt="galaxy5" src="https://user-images.githubusercontent.com/28693536/178962930-7e7c0f8b-f473-4c94-83f7-1c874697d3a6.PNG">
<img width="871" alt="galaxy6" src="https://user-images.githubusercontent.com/28693536/178962967-8fc4d926-f214-411c-806f-be4f6627ad1a.PNG">
<img width="872" alt="galaxy7" src="https://user-images.githubusercontent.com/28693536/178962984-d1f5723c-9c2b-4dd0-8030-43828ac75a70.PNG">
